name: "NUnit HTML Report"
description: "Generates an HTML report from NUnit XML test results"
inputs:
  inputXmlPath:
    description: "XML input file path"
    required: true
  outputHtmlPath:
    description: "HTML output file path"
    default: ""
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - run: sudo python -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - run: sudo python ${{ github.action_path }}/main.py ${{ inputs.inputXmlPath }} ${{ inputs.outputHtmlPath }}
      shell: bash
branding:
  icon: "file"
  color: "green"
